### PR TITLE
Handle parsing foo &:bar correctly

### LINKED ISSUE #1144: Incorrect parsing of `foo &:bar`
Method call with `&object` argument is correctly parsed when parentheses are present:

```
bin/parse -e 'foo(&:to_s)'
#<YARP::ParseResult:0x0000000108612db8
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00000001086eeb10 @offsets=[0], @source="foo(&:to_s)">,
 @value=
  ProgramNode(0...11)(
    [],
    StatementsNode(0...11)(
      [CallNode(0...11)(
         nil,
         nil,
         (0...3),
         (3...4),
         ArgumentsNode(4...10)([BlockArgumentNode(4...10)(SymbolNode(5...10)((5...6), (6...10), nil, "to_s"), (4...5))]),
         (10...11),
         nil,
         0,
         "foo"
       )]
    )
  ),
 @warnings=[]>
```

But when parentheses are omitted a method call is parsed incorrectly as `foo.&(symbol)`:

```
bin/parse -e 'foo &:to_s'
#<YARP::ParseResult:0x000000010e5e77c0
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00000001110ceda8 @offsets=[0], @source="foo &:to_s">,
 @value=
  ProgramNode(0...10)(
    [],
    StatementsNode(0...10)(
      [CallNode(0...10)(
         CallNode(0...3)(nil, nil, (0...3), nil, nil, nil, nil, 0, "foo"),
         nil,
         (4...5),
         nil,
         ArgumentsNode(5...10)([SymbolNode(5...10)((5...6), (6...10), nil, "to_s")]),
         nil,
         nil,
         0,
         "&"
       )]
    )
  ),
 @warnings=[]>
```

### PR DESCRIPTION
**Pull request by kddnewton**
Fixes #1144

### CODE REVIEW

File: test/newline_test.rb [hunk 1]
```diff
@@ -38,15 +38,15 @@ def visit(node)
...
-        expected.delete(578)
+        actual.delete(578)
+        expected.delete(579)
         # extra flag for: lex_state =\n  if RIPPER: due to bytecode order
-        actual.delete(610)
+        actual.delete(611)
         # extra flag for: (token[2].start_with?("\#$") || token[2].start_with?("\#@"))
         # unclear when ParenthesesNode should allow a second flag on the same line or not
-        actual.delete(737)
+        actual.delete(738)
```
Comment (eregon) [inline test/newline_test.rb:49]: These are rather annoying to update, not sure if there is a good solution.
FWIW for serialize.rb I changed it to find the line automatically: https://github.com/ruby/yarp/commit/5de581923103911d7eba1019528a5827ecf3a980#diff-bcb8a82557341f407dbe084da75234f3139581f75d4c23d0c0e272af5aef12aa
