### PR TITLE
Handle missing clauses in case statement

### LINKED ISSUE #1501: `case 1; end` should be rejected
A `case` clause with no `when` clause must be rejected.

```
$ ./local/bin/irb -ryarp
irb(main):001> RubyVM::AbstractSyntaxTree.parse("case 1; end")
<internal:ast>:59:in `parse': syntax error, unexpected `end', expecting `when' (SyntaxError)
case 1; end
        ^~~

        from (irb):1:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /home/mame/work/ruby/local/lib/ruby/gems/3.3.0+0/gems/irb-1.8.1/exe/irb:9:in `<top (required)>'
        from ./local/bin/irb:25:in `load'
        from ./local/bin/irb:25:in `<main>'
irb(main):002> YARP.parse("case 1; end")
=>
#<YARP::ParseResult:0x00007fbe4a1037a8
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00007fbe49f2d7d0 @offsets=[0], @source="case 1; end">,
 @value=
  @ ProgramNode (location: (0...11))
├── locals: []
└── statements:
    @ StatementsNode (location: (0...11))
    └── body: (length: 1)
        └── @ CaseNode (location: (0...11))
            ├── predicate:
            │   @ IntegerNode (location: (5...6))
            │   └── flags: decimal
            ├── conditions: (length: 0)
            ├── consequent: ∅
            ├── case_keyword_loc: (0...4) = "case"
            └── end_keyword_loc: (8...11) = "end",
 @warnings=[]>
```

### PR DESCRIPTION
**Pull request by kddnewton**
Fixes #1501

### CODE REVIEW

File: test/yarp/errors_test.rb [hunk 1]
```diff
@@ -923,7 +923,7 @@ def test_case_without_when_clauses_errors_on_else_clause
       )
 
       assert_errors expected, "case :a\nelse\nend", [
-        ["Unexpected `else` in `case` statement; a `when` clause must precede `else`", 8..12]
+        ["Expected a `when` or `in` clause after `case`", 0..4]
```
Comment (paracycle) [inline test/yarp/errors_test.rb:926]: Shouldn't we be adding a new test for the actual reported case in #1501, as well as updating the expectation of this test? Something like https://github.com/ruby/yarp/pull/1518/files#diff-7053a965faa5dfe2508b5e2e53dd765e7ec99bdfb2855555a10a1fae92157dd1R930-R943, for example.

Comment (kddnewton) [reply test/yarp/errors_test.rb:952]: Updated!

**Review by HParker — APPROVED** [review]
